language: erlang

before_install:
       - wget https://raw.github.com/wiki/rebar/rebar/rebar
       - chmod +x rebar

script: "make get-deps compile test docs"

otp_release:
   - 19.1
   - 18.3
   - 17.5
   - R16B03-1
